algoritmo "exercicio-44 contando com começo, final e pulo"
var
inicioC, finalC, inc: inteiro
inicio

      escreva("Digite o valor inicial da contagem: ")
      leia(inicioC)
      escreva("Digite o valor final da contagem: ")
      leia(finalC)
      escreva("Digite o incremento da contagem: ")
      leia(inc)
      
      escreval

      enquanto (inicioC <= finalC) faca
         escreva(inicioC)
         inicioC <- inicioC + inc
      fimenquanto
      escreva(" Acabou!")

fimalgoritmo
