algoritmo "exercicio-26 comparando 2 valores"
// Função :
// Autor :
// Data : 19/07/2020
// Seção de Declarações 
var

   valor1, valor2: inteiro

inicio

      escreva("Digite 1º valor: ")
      leia(valor1)
      escreva("Digite 2º valor: ")
      leia(valor2)
      
      se (valor1 > valor2) entao
         escreval(valor1," é maior que",valor2)
      senao
         escreval(valor2," é maior que",valor1)
      fimse

fimalgoritmo
