algoritmo "exercicio-2 boas-vindas usuario"
// Função : Mensagem de boas vindas ao usuario
// Autor : Guilherme Artigas
// Data : 12/07/2020
// Seção de Declarações 
var

   usuario: caractere

inicio

      escreval("Olá seja bem vindo!")
      escreval
      escreva("Qual é o seu nome: ")
      leia(usuario)
      escreval
      escreval("Obrigado por estar aqui ", usuario, " é um prazer conhece-lo!")

fimalgoritmo
