algoritmo "exercicio-6 antecessor e sucessor"
// Função : lê número inteiro e apresente antecessor e sucessor
// Autor : Guilherme Artigas
// Data : 12/07/2020
// Seção de Declarações 
var

   numero: inteiro

inicio

      escreval("Olá seja bem vindo!")
      escreval
      escreva("Digite um número inteiro: ")
      leia(numero)
      escreval
      escreval("O antecessor de ", numero, " é: ", numero - 1)
      escreval("O sucessor de ", numero, " é: ", numero + 1)

fimalgoritmo
