algoritmo "exercicio-11 equação segundo grau"
// Função :
// Autor :
// Data : 14/07/2020
// Seção de Declarações 
var

   a, b, c, delta: real

inicio

      escreva("Digite o valor de A: ")
      leia(a)
      escreva("Digite o valor de B: ")
      leia(b)
      escreva("Digite o valor de C: ")
      leia(c)
      
      delta <- (-b ^ 2) -4 * a * c
      
      escreval("Valor de delta:", delta)

fimalgoritmo
