algoritmo "exercicio-12 produto com 5% de desconto"
// Função :
// Autor :
// Data : 14/07/2020
// Seção de Declarações 
var

   valor_produto: real

inicio

      escreva("Digite o valor do produto R$ ")
      leia(valor_produto)
      valor_produto <- valor_produto - (valor_produto * 5 / 100)
      escreval
      escreval("O valor do Produto digitado com 5% de desconto é R$",valor_produto:5:2)

fimalgoritmo
