algoritmo "exercicio-88 passagem parametros de 2 tipos na mesma Proced"
var

   Procedimento gerador(par1:caractere; par2:inteiro)
   Var
   
   Inicio
   
         escreval("+------=====-------+")
         para par2 <- 1 ate 4 passo 1 faca
            escreval(par1)
         fimpara
         escreval("+------=====-------+")
   
   FimProcedimento

inicio

      gerador("Aprendendo Portugol",4)

fimalgoritmo
