algoritmo "exercicio-3 nome e salario"
// Função : Nome e salário do usuario
// Autor : Guilherme Artigas
// Data : 12/07/2020
// Seção de Declarações 
var

   usuario: caractere
   salario: real

inicio

      escreval("Olá, seja bem vindo!")
      escreva("Digite seu nome: ")
      leia(usuario)
      escreva("Digite o valor do seu salário: R$ ")
      leia(salario)
      escreval("O funcionário ", usuario, " tem um salário de R$", salario, " em junho.")

fimalgoritmo
