algoritmo "exercicio-13 aumento 15% no salario"
// Função :
// Autor :
// Data : 14/07/2020
// Seção de Declarações 
var

   salario_f: real

inicio

      escreva("Digite o valor do seu Salario R$")
      leia(salario_f)
      salario_f <- salario_f + (salario_f * 15 / 100)
      escreval
      escreval("Parabens, voce ganhou 15% de aumento!")
      escreval("seu novo salario é R$",salario_f:5:2)

fimalgoritmo
