algoritmo "exercicio-7 dobro e terça parte"
// Função : lê um número apresenta o seu dobro e a sua terça parte
// Autor : Guilherme Artigas
// Data : 12/07/2020
// Seção de Declarações 
var

   numero: real

inicio

      escreva("Digite qualquer número/valor: ")
      leia(numero)
      escreval("O dobro de ", numero, " é: ", numero * 2)
      escreval("A terça parte de ", numero, " é: ", numero / 3)

fimalgoritmo
