algoritmo "idade-creuza"
// Função : calcúlo de idade
// Autor : Guilherme Artigas
// Data : 13/07/2020
// Seção de Declarações 
var

   ano_atual, ano_nasc, idade: inteiro

inicio

      escreval("Olá bem vindo!")
      escreval
      escreval("Em que ano nós estamos?")
      leia(ano_atual)
      escreval("Qual o ano do seu nascimento?")
      leia(ano_nasc)
      idade <- ano_atual - ano_nasc
      escreval
      escreval("Então sua idade é", idade, " anos.")

fimalgoritmo
